name: Sonarcloud Analysis

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Switch to Jakarta Time Zone
      run: |
        sudo timedatectl set-timezone Asia/Jakarta
    - name: Sonar Scan by Sonarcloud
      run: |
        mvn clean install && mvn org.jacoco:jacoco-maven-plugin:prepare-agent install && mvn sonar:sonar -Dsonar.projectKey=function-future_function-backend -Dsonar.organization=function-future -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
